**Import Necessary Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [2]:
data = pd.read_csv('Iris.csv')

In [3]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [4]:
data.drop(['Id'],axis=1,inplace=True)

KeyError: "['Id'] not found in axis"

In [5]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [7]:
x_train.shape

(112, 4)

In [8]:
x_test.shape

(38, 4)

In [9]:
y_train.shape

(112,)

In [10]:
y_test.shape

(38,)

In [11]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train_new = sc.fit_transform(x_train)
x_test_new = sc.transform(x_test)

In [12]:
x_test

,sepal_length,sepal_width,petal_length,petal_width
114,5.8,2.8,5.1,2.4
62,6.0,2.2,4.0,1.0
33,5.5,4.2,1.4,0.2
107,7.3,2.9,6.3,1.8
7,5.0,3.4,1.5,0.2
100,6.3,3.3,6.0,2.5
40,5.0,3.5,1.3,0.3
86,6.7,3.1,4.7,1.5
76,6.8,2.8,4.8,1.4
71,6.1,2.8,4.0,1.3


In [13]:
from sklearn.svm import SVC
svm_classifier = SVC()
svm_classifier.fit(x_train,y_train)

SVC()

In [14]:
y_pred = svm_classifier.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [16]:
from sklearn.svm import SVC
svm_classifier2 = SVC(kernel='linear')
svm_classifier2.fit(x_train,y_train)

SVC(kernel='linear')

In [17]:
y_pred_2 = svm_classifier2.predict(x_test)

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_2)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [19]:
from sklearn.svm import SVC
svm_classifier3 = SVC(kernel='poly')
svm_classifier3.fit(x_train,y_train)

SVC(kernel='poly')

In [20]:
y_pred_3 = svm_classifier3.predict(x_test)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_3)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [22]:
from sklearn.svm import SVC
svm_classifier4 = SVC(kernel='sigmoid')
svm_classifier4.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [23]:
y_pred_4 = svm_classifier4.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_4)
cm

array([[ 0,  0, 13],
       [ 0,  0, 16],
       [ 0,  0,  9]], dtype=int64)

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(criterion='entropy')
rfc.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy')

In [26]:
y_pred_rfc = rfc.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred_rfc))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [29]:
from sklearn.ensemble import RandomForestClassifier
rfc1 = RandomForestClassifier(n_estimators=10,criterion='entropy')
rfc1.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [30]:
y_pred_rfc1 = rfc1.predict(x_test)

In [31]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred_rfc1))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [35]:
from sklearn.ensemble import RandomForestClassifier
rfc2 = RandomForestClassifier(n_estimators=20,criterion='entropy')
rfc2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=20)

In [36]:
y_pred_rfc2 = rfc2.predict(x_test)

In [37]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred_rfc2))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [38]:
from sklearn.ensemble import RandomForestClassifier
rfc3 = RandomForestClassifier(n_estimators=30,criterion='entropy')
rfc3.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [39]:
y_pred_rfc3 = rfc3.predict(x_test)

In [40]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred_rfc3))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [41]:
from sklearn.ensemble import RandomForestClassifier
rfc4 = RandomForestClassifier(n_estimators=40,criterion='entropy')
rfc4.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=40)

In [42]:
y_pred_rfc4 = rfc4.predict(x_test)

In [43]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred_rfc4))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [44]:
from sklearn.ensemble import RandomForestClassifier
rfc5 = RandomForestClassifier(n_estimators=50,criterion='entropy')
rfc5.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=50)

In [45]:
y_pred_rfc5 = rfc5.predict(x_test)

In [46]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred_rfc5))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
